version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

    environment:
      DOCKER_IMAGE_NAME: bilalbaree/devsec_a3

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake cppcheck clang sonar-scanner python3 python3-pip
            pip3 install cpp-coveralls

      - run:
          name: Static Code Analysis - Cppcheck
          command: |
            cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 .

      - run:
          name: Create build directory and run CMake
          command: |
            mkdir -p build
            cd build
            cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
            make

      - run:
          name: Run Unit Tests (if you have any)
          command: |
            echo "Running unit tests..."
            # ./build/test_executable  # Uncomment if tests exist

      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization=bilalbaree \
              -Dsonar.projectKey=Devsec_A3_New \
              -Dsonar.sources=. \
              -Dsonar.cfamily.compile-commands=build/compile_commands.json \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=$SONAR_TOKEN

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_IMAGE_NAME .

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_IMAGE_NAME

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
