version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install build tools
          command: |
            sudo apt update
            sudo apt install -y cmake g++ clang
      - run:
          name: Build project
          command: |
            mkdir -p build
            cd build
            cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            make
      - persist_to_workspace:
          root: .
          paths:
            - build/compile_commands.json  # Persisting compile_commands.json for later use

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - attach_workspace:
          at: .  # Attaching the workspace so the build artifacts can be used
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization=bilalbaree \
              -Dsonar.projectKey=Devsec_A3_New \
              -Dsonar.sources=src  # Ensure this points to the correct source directory
              -Dsonar.cfamily.compile-commands=build/compile_commands.json \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=$SONAR_TOKEN

  dockerize:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specifying Docker version for compatibility
      - run:
          name: Build Docker Image
          command: |
            docker build -t bilalbaree/devsec_a3 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "bilalbaree" --password-stdin
            docker push bilalbaree/devsec_a3

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - sonarqube:
          requires:
            - build
      - dockerize:
          requires:
            - build
