version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Using Python 3.8 base image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Create a virtual environment
            . venv/bin/activate   # Activate the virtual environment
            pip install --upgrade pip  # Upgrade pip
      - persist_to_workspace:
          root: . 
          paths:
            - .  # Save the whole workspace if necessary for the next steps

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check if SonarQube is enabled
          command: |
            if [ "$SONARQUBE_ENABLED" == "1" ]; then
              echo "Running SonarQube Analysis..."
              sonar-scanner \
                -Dsonar.organization=bilalbaree \
                -Dsonar.projectKey=BilalBaree_Devsec_A3_New \
                -Dsonar.sources=. \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.token=$SONAR_TOKEN
            else
              echo " ."
            fi

  dockerize:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            # Assuming you have a Dockerfile in your project directory
            docker build -t bilalbaree/devsec_a3 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "bilalbaree" --password-stdin
            docker push bilalbaree/devsec_a3

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - sonarqube:
          requires:
            - build
      - dockerize:
          requires:
            - build
